@startuml

interface UserAction {
    + {abstract} signin(): void
    + {abstract} signout(): void
    + {abstract} register(): void
    + {abstract} forget(): void
}

class User implements UserAction

class UserActionProxy implements UserAction {
    - target: User
    + UserActionProxy(target: User): UserActionProxy
}

class Main

User <--o UserActionProxy

Main ..> User
Main ..> UserActionProxy

@enduml